// Code generated by mockery v1.0.0
package db

import mock "github.com/stretchr/testify/mock"

// MockTransport is an autogenerated mock type for the Transport type
type MockTransport struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ID
func (_m *MockTransport) Delete(ID string) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: data
func (_m *MockTransport) FindAll(data interface{}) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ID, data
func (_m *MockTransport) FindByID(ID string, data interface{}) error {
	ret := _m.Called(ID, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(ID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: data
func (_m *MockTransport) Insert(data interface{}) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
